import 'dart:math' as math;

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

/// Byproduct types generated by a harvest, each routed to a registered
/// industrial buyer. [acceptedByLabel] hints at the buyer category.
enum ByproductType {
  coconutHusk,
  coconutShell,
  jackfruitRags,
  arecaWaste;

  String get label => switch (this) {
        ByproductType.coconutHusk => 'Coconut husks',
        ByproductType.coconutShell => 'Coconut shells',
        ByproductType.jackfruitRags => 'Jackfruit rags',
        ByproductType.arecaWaste => 'Areca waste',
      };

  /// Firestore value matched against `byproduct_buyers.acceptsTypes`.
  String get firestoreValue => switch (this) {
        ByproductType.coconutHusk => 'coconut_husk',
        ByproductType.coconutShell => 'coconut_shell',
        ByproductType.jackfruitRags => 'jackfruit_rags',
        ByproductType.arecaWaste => 'areca_waste',
      };

  String get buyerHint => switch (this) {
        ByproductType.coconutHusk => 'Coir units',
        ByproductType.coconutShell => 'Charcoal / shell craft',
        ByproductType.jackfruitRags => 'Dairy farms',
        ByproductType.arecaWaste => 'Compost / board mills',
      };

  IconData get icon => switch (this) {
        ByproductType.coconutHusk => Icons.grass_outlined,
        ByproductType.coconutShell => Icons.egg_outlined,
        ByproductType.jackfruitRags => Icons.agriculture_outlined,
        ByproductType.arecaWaste => Icons.compost_outlined,
      };

  static ByproductType? fromString(String? v) {
    for (final t in ByproductType.values) {
      if (t.firestoreValue == v) return t;
    }
    return null;
  }
}

/// A registered industrial buyer — `/byproduct_buyers/{uid}`.
class ByproductBuyer {
  final String id;
  final String name;
  final List<ByproductType> acceptsTypes;
  final GeoPoint? location;

  const ByproductBuyer({
    required this.id,
    required this.name,
    this.acceptsTypes = const [],
    this.location,
  });

  factory ByproductBuyer.fromFirestore(String id, Map<String, dynamic> data) {
    return ByproductBuyer(
      id: id,
      name: data['name'] as String? ?? '',
      acceptsTypes: ((data['acceptsTypes'] as List?) ?? const [])
          .map((e) => ByproductType.fromString(e.toString()))
          .whereType<ByproductType>()
          .toList(),
      location: data['location'] as GeoPoint?,
    );
  }

  /// Great-circle distance in km from [from] to this buyer (0 if unknown).
  double distanceKmFrom(GeoPoint? from) {
    if (from == null || location == null) return 0;
    return _haversineKm(
        from.latitude, from.longitude, location!.latitude, location!.longitude);
  }
}

/// A routing record written to `/byproduct_routes/{routeId}`.
class ByproductRoute {
  final ByproductType type;
  final double weightKg;
  final String buyerId;
  final String buyerName;

  const ByproductRoute({
    required this.type,
    required this.weightKg,
    required this.buyerId,
    required this.buyerName,
  });
}

double _haversineKm(double lat1, double lon1, double lat2, double lon2) {
  const r = 6371.0;
  final dLat = _rad(lat2 - lat1);
  final dLon = _rad(lon2 - lon1);
  final a = math.sin(dLat / 2) * math.sin(dLat / 2) +
      math.cos(_rad(lat1)) *
          math.cos(_rad(lat2)) *
          math.sin(dLon / 2) *
          math.sin(dLon / 2);
  return r * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a));
}

double _rad(double deg) => deg * math.pi / 180;
